name: Build Switch NRO
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto-generate working Makefile
        run: |
          cat << 'EOF' > Makefile
          ifeq ($(strip $(DEVKITPRO)),)
          $(error "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>/devkitpro")
          endif

          TOPDIR ?= $(CURDIR)
          include $(DEVKITPRO)/libnx/switch_rules

          TARGET := rickrolled
          BUILD := build
          SOURCES := source
          DATA := data
          INCLUDES := include

          EXEFS_SRC := exefs

          APP_TITLE := RICKROLLED
          APP_AUTHOR := User
          APP_VERSION := 1.0.0

          include $(DEVKITPRO)/devkitA64/base_rules
          EOF

      - name: Compile NRO
        run: |
          make

      - name: Upload NRO Result
        uses: actions/upload-artifact@v4
        with:
          name: switch-executable
          path: |
            *.nro
            
