name: Build Switch Scream Maze
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Valid Makefile with Tabs
        run: |
          # Автоматически генерируем правильный Makefile с использованием настоящей табуляции \t
          # Это решает проблему "No targets. Stop" раз и навсегда
          printf "ifeq (\$(strip \$(DEVKITPRO)),)\n\$(error \"Please set DEVKITPRO\")\nendif\n\ninclude \$(DEVKITPRO)/libnx/switch_rules\n\nTARGET := gemini\nBUILD := build\nSOURCES := source\n\nAPP_TITLE := SCARY MAZE\nAPP_AUTHOR := User\nAPP_VERSION := 1.0.0\n\ninclude \$(DEVKITPRO)/devkitA64/base_rules\n" > Makefile

      - name: Compile via Official Toolchain
        run: |
          # Запускаем официальную сборку, которая правильно создаст и вшьет все NACP заголовки
          make

      - name: Upload NRO Result
        uses: actions/upload-artifact@v4
        with:
          name: switch-executable
          path: |
            *.nro
            
